### PR TITLE
Ziegler-Nicols kiln-tuner

### PR DESCRIPTION
**Pull request by adq**
Hi, I ended up building a Ziegler-Nicols PID tuning tool, kiln-tuner.py.

I had to modify oven.py slightly so I could have complete control over the heating process.

I added a doc on how to use it.

Note: I find these values didn't work very well with the code as it was due to the integral windup problem. However, I've been playing with methods to avoid that, and I've also just seen your own patch for it. I'll give it a test and report back!

### CODE REVIEW

**Comment by adq** [comment]
Do you think this should be changed to use the oven.py PID controller set to 1/0/0 rather than what its doing right now? Easy enough for me to change it (I could even just override the config internally at runtime so people don't have to manually change config.py).

**Comment by jbruce12000** [comment]
setting the PID to 1,0,0 is the same as no control at all which is what it is doing right now. I don't think you need to make a change.

**Comment by jbruce12000** [comment]
tested the ZN tuner last night. Worked well. Had trouble with the f-string printing. I'm gonna merge, then go back and change those to old school print statements so they work with python 3.5.

**Comment by kendrick90** [comment]
I tested this out today and had a little bit of frustration on a couple of runs because the temperature fluctuated while crossing 400 and went back down, prematurely ending the cooling phase.

**Pull request merged**
